#!/usr/bin/env python3
"""ADR consolidation (ideas.md 1, part 3): gather every repository's docs/adr/ into one
namespaced tree with a single index, for the org docs repository.

  adr_consolidate.py --out adr --repos owner/a owner/b [--token TOKEN] [--ref-map a=nightly]
  adr_consolidate.py --out adr --repos-file repos.txt [--clone-dir /tmp/x]

Layout produced:
  <out>/<repo-name>/adr-NNN-*.md    (verbatim copies; relative links rewritten to stay valid)
  <out>/README.md                   (index: repo, number, title, status, date, ticket)
Standard library only; uses `git` for shallow clones.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HEADER_RE = {
    "date": re.compile(r"^\s*-\s*\*\*Date:\*\*\s*(.+)$", re.M),
    "status": re.compile(r"^\s*-\s*\*\*Status:\*\*\s*(.+)$", re.M),
    "ticket": re.compile(r"^\s*-\s*\*\*Ticket:\*\*\s*(.+)$", re.M),
}
TITLE_RE = re.compile(r"^#\s+(ADR-(\d+)):?\s*(.+)$", re.M)
LINK_RE = re.compile(r"\]\((?!https?://|#|/)([^)]+)\)")


def read_repos_file(path: Path) -> list[str]:
    return [l.split("#", 1)[0].strip() for l in path.read_text().splitlines() if l.split("#", 1)[0].strip() and "/" in l]


def clone(repo: str, ref: str | None, token: str | None, dest: Path) -> bool:
    url = f"https://github.com/{repo}.git" if not token else f"https://x-access-token:{token}@github.com/{repo}.git"
    cmd = ["git", "clone", "--depth", "1", "--filter=blob:none", "--no-checkout", "-q"]
    if ref:
        cmd += ["--branch", ref]
    cmd += [url, str(dest)]
    if subprocess.run(cmd, capture_output=True).returncode != 0:
        return False
    return subprocess.run(["git", "-C", str(dest), "checkout", "-q", "HEAD", "--", "docs/adr"], capture_output=True).returncode == 0


def parse(md: str) -> dict:
    m = TITLE_RE.search(md)
    info = {"number": int(m.group(2)) if m else 0, "title": (m.group(3).strip() if m else "(untitled)")}
    for k, rx in HEADER_RE.items():
        mm = rx.search(md)
        info[k] = mm.group(1).strip() if mm else ""
    return info


def rewrite_links(md: str, repo_name: str) -> str:
    # links to sibling ADRs stay relative (same folder); anything else becomes a repo-relative note
    def fix(m):
        target = m.group(1)
        if target.startswith("adr-") or target.startswith("./adr-"):
            return m.group(0)
        return f"]({target} \"in {repo_name}\")"
    return LINK_RE.sub(fix, md)


def consolidate(repos: list[str], out: Path, token: str | None, ref_map: dict[str, str], clone_dir: Path) -> list[dict]:
    rows: list[dict] = []
    out.mkdir(parents=True, exist_ok=True)
    for repo in repos:
        name = repo.split("/", 1)[1]
        dest = clone_dir / name
        shutil.rmtree(dest, ignore_errors=True)
        if not clone(repo, ref_map.get(name) or ref_map.get(repo), token, dest):
            print(f"{repo}: no docs/adr (or clone failed); skipped")
            continue
        src = dest / "docs" / "adr"
        target = out / name
        shutil.rmtree(target, ignore_errors=True)
        target.mkdir(parents=True)
        for f in sorted(src.glob("adr-*.md")):
            md = f.read_text(encoding="utf-8", errors="replace")
            (target / f.name).write_text(rewrite_links(md, name), encoding="utf-8")
            info = parse(md)
            info.update({"repo": name, "file": f"{name}/{f.name}"})
            rows.append(info)
        print(f"{repo}: {len(list(target.glob('adr-*.md')))} ADR(s)")
    rows.sort(key=lambda r: (r["repo"], r["number"]))
    lines = ["# Architecture Decision Records — all repositories", "",
             "Generated by `adr_consolidate.py`; the write side is each repository's own `docs/adr/`. Do not edit here.", "",
             "| Repo | ADR | Title | Status | Date | Ticket |", "|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['repo']} | [ADR-{r['number']:03d}]({r['file']}) | {r['title']} | {r['status']} | {r['date']} | {r['ticket']} |")
    stale = [r for r in rows if r["status"].lower().startswith("proposed")]
    lines += ["", f"**Roll-up:** {len(rows)} ADRs across {len({r['repo'] for r in rows})} repositories; {len(stale)} still Proposed.", ""]
    (out / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--repos", nargs="*", default=[])
    ap.add_argument("--repos-file", type=Path)
    ap.add_argument("--token", default=None)
    ap.add_argument("--ref-map", nargs="*", default=[], help="repo-name=branch overrides")
    ap.add_argument("--clone-dir", type=Path, default=None)
    args = ap.parse_args(argv)
    repos = list(args.repos) + (read_repos_file(args.repos_file) if args.repos_file else [])
    if not repos:
        print("adr_consolidate: no repositories")
        return 2
    ref_map = dict(kv.split("=", 1) for kv in args.ref_map)
    clone_dir = args.clone_dir or Path(tempfile.mkdtemp(prefix="adr-"))
    rows = consolidate(repos, args.out, args.token, ref_map, clone_dir)
    print(f"index: {args.out / 'README.md'} ({len(rows)} ADRs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
