#!/usr/bin/env python3
"""Every commit carries a Jira key prefix `<PROJECT>-NNN:` (org rule; ideas.md 7).

Exempt: merge commits, bot commits (org-config-sync, release-bot, rollback-bot,
dependabot, renovate), back-merge and revert subjects generated by the org workflows.

  check_commits.py --range base..head [--root .]
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import annotate, commits, parse_common  # noqa: E402

PREFIX = re.compile(r"^[A-Z][A-Z0-9]{1,9}-\d+: \S")
BOT_AUTHORS = ("org-config-sync", "release-bot", "rollback-bot", "dependabot", "renovate", "github-actions")
EXEMPT_SUBJECTS = (
    re.compile(r"^Merge "),
    re.compile(r"^Back-merge "),
    re.compile(r"^Rollback "),
    re.compile(r"^Revert \""),
    re.compile(r"^docs: auto-generate workflow documentation$"),
)


def keys_in(subject: str) -> set[str]:
    return set(re.findall(r"\b[A-Z][A-Z0-9]{1,9}-\d+\b", subject))


def main(argv: list[str] | None = None) -> int:
    ap = parse_common(argv or sys.argv[1:], __doc__)
    args = ap.parse_args(argv)
    if not args.rng:
        print("check_commits: --range base..head is required")
        return 2
    root: Path = args.root.resolve()
    bad = 0
    keys: set[str] = set()
    for sha, author, subject in commits(root, args.rng):
        if any(b in author for b in BOT_AUTHORS) or any(rx.match(subject) for rx in EXEMPT_SUBJECTS):
            continue
        if PREFIX.match(subject):
            keys |= keys_in(subject.split(":", 1)[0])
        else:
            annotate("error", f"commit {sha[:7]} lacks a ticket prefix `<PROJECT>-NNN: ` — subject: {subject!r}")
            bad += 1
    if args.json:
        import json
        print(json.dumps({"bad": bad, "tickets": sorted(keys)}))
    else:
        print(f"commits: {'ok' if not bad else str(bad) + ' without ticket prefix'}; tickets: {', '.join(sorted(keys)) or '-'}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
